import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "seerportal-api",
    },
    {
      type: "category",
      label: "User Details",
      link: {
        type: "doc",
        id: "user-details",
      },
      items: [
        {
          type: "doc",
          id: "login",
          label: "Login",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "forgot-password",
          label: "Forgot password",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "register",
          label: "New user registration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "totp-secret-generation",
          label: "TOTP secret generation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "totp-validation",
          label: "TOTP validation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "user-management-unlock",
          label: "User management unlock",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "user-profile-update",
          label: "User profile update",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reset-2-fa-settings",
          label: "Reset 2FA settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "user-upload",
          label: "User upload",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "user-upload-via-table",
          label: "User upload via table",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "verify-user-account",
          label: "Verify user account",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reset-users-password",
          label: "Reset user's password",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-user-data",
          label: "Get user data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-user-details",
          label: "Get user details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "change-user-password",
          label: "Change user password",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "change-password-with-key-and-token",
          label: "Change password with key and token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-reset-password-link",
          label: "Get reset password link",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "delete-user-account",
          label: "Delete user account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "logout-user",
          label: "Logout user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "check-token-validity",
          label: "Check token validity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-user-role",
          label: "Update user role",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-email-verification-link",
          label: "Get email verification link",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "download-user-data",
          label: "Download user data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "user-activity-report",
          label: "User activity report",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "user-activity-alert-report",
          label: "User activity alert report",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "user-activity-case-report",
          label: "User activity case report",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "user-activity-session-report",
          label: "User activity session report",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "password-length",
          label: "Password length",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "restore-login-attempts",
          label: "Restore login attempts.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "user-session-logins-report",
          label: "User session logins report",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "user-report-program-and-role-list",
          label: "User report, program and role list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "user-list",
          label: "User list",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Home Page",
      link: {
        type: "doc",
        id: "home-page",
      },
      items: [
        {
          type: "doc",
          id: "get-alert-details",
          label: "Get alert details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-case-details",
          label: "Get case details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-fin-sar-details",
          label: "Get FinSar details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-menu-permitted-list",
          label: "Get menu permitted list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-last-updated-date-and-time",
          label: "Get last updated date and time",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-last-updated-date-and-time",
          label: "Get last updated date and time",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-last-updated-date-and-time",
          label: "Get last updated date and time",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-last-updated-date-and-time",
          label: "Get last updated date and time",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-metric-details",
          label: "Get metric details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-last-viewed-alerts",
          label: "Get last viewed alerts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-most-viewed-alerts",
          label: "Get most viewed alerts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-last-viewed-reports",
          label: "Get last viewed reports",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-most-viewed-reports",
          label: "Get most viewed reports",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-menu-module-list",
          label: "Get menu module list",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Admin & Billing",
      link: {
        type: "doc",
        id: "admin-billing",
      },
      items: [
        {
          type: "doc",
          id: "list-of-clients",
          label: "List of clients",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-of-states-with-respective-country-name",
          label: "List of states with respective country name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-of-countries",
          label: "List of countries",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-new-client",
          label: "Add  new client",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-client",
          label: "Update client",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-sar-users",
          label: "List of SAR users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-new-user",
          label: "Add new user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-user",
          label: "Update user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-users",
          label: "List of  users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-impersonate-client-name",
          label: "Get impersonate client name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-role-program-group-report-group-and-cluster-details-of-impersonate-user",
          label: "Get role, program group, report group and cluster details of impersonate user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-show-impersonate-details",
          label: "To show impersonate details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "add-impersonate-user",
          label: "Add impersonate user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-impersonate-user",
          label: "Update impersonate user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-the-impersonate-user",
          label: "Delete the impersonate user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "impersonate-user-login",
          label: "Impersonate user login",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "add-new-role",
          label: "Add new role",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-role",
          label: "Update role",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "user-details-with-mentioned-role-id",
          label: "User details with mentioned role ID",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "alert-escalation-list",
          label: "Alert escalation list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-role-list",
          label: "Get role list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-change-the-status-of-role",
          label: "To change the status of role",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-list-of-data-admin-users",
          label: "Get list of data admin users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-of-program-groups",
          label: "List of program groups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "save-program-group",
          label: "Save program group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-program-group",
          label: "Update program group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-program-group-by-id",
          label: "Get program group by id",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-the-program-group",
          label: "Delete the Program group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-update-program-group-for-user",
          label: "To update program group for user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-report-groups",
          label: "List of report groups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "save-report-group",
          label: "Save report group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-report-group",
          label: "Update report group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-details-of-report-group",
          label: "Get details of report group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-report-group",
          label: "Delete report group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "listing-of-the-clusters-running-on-the-system",
          label: "Listing of the clusters running on the system",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "details-about-tokens",
          label: "Details about tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "ds-list",
          label: "DSList",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-cluster-history-list",
          label: "Get cluster-history list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "cluster-details",
          label: "Cluster details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "update-cluster-status",
          label: "Update cluster status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "add-cluster",
          label: "Add cluster",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-cluster",
          label: "Update cluster",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-cluster-details-about-the-respective-user",
          label: "Get cluster details about the respective user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-assign-cluster-to-the-user",
          label: "To assign cluster to the user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "shows-all-the-work-units-that-have-run-in-the-system",
          label: "Shows all the WorkUnits that have run in the system.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "active-role-list",
          label: "Active role list",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-respective-token-details",
          label: "Get respective token details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-list-by-type",
          label: "Get list by type",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-api-key",
          label: "Add API key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-api-key",
          label: "Update API key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-all-keys-on-the-platform",
          label: "List of all keys on the platform",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-of-crons",
          label: "List of crons",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-of-cron-clients",
          label: "List of cron Clients",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-of-common-crons",
          label: "List of common crons",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "cron-logs",
          label: "Cron logs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-cron-details-with-mentioned-id",
          label: "Get cron details with mentioned ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-cron",
          label: "Add Cron",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-cron-setting",
          label: "Update Cron setting",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "get-list-of-crons",
          label: "Get list of crons",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-download-the-audit-log-data",
          label: "To download the audit log data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "provides-detailed-and-documented-evidence-of-the-sequence-of-activities",
          label: "Provides detailed and documented evidence of the sequence of activities",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-operation-types",
          label: "List of operation types",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-feature-list",
          label: "Get feature List",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-all-invoices",
          label: "List of all invoices",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-descrptive-invoice-details-for-selected-id",
          label: "Get descrptive invoice details for selected ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "create-audit-log",
          label: "Create Audit Log",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-a-list-of-email-notifications",
          label: "Get a list of email notifications",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-downloaded-reports",
          label: "List of downloaded reports",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "downloaded-the-file-from-the-download-center",
          label: "Downloaded the file from the download Center",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-download-the-alert",
          label: "To download the alert",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "download-a-report",
          label: "Download a report",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "give-list-of-event-type",
          label: "Give list of event type",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "resend-event",
          label: "Resend event",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-webhook-id-data",
          label: "Get webhook id data",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Rules & MDM",
      link: {
        type: "doc",
        id: "rules-mdm",
      },
      items: [
        {
          type: "doc",
          id: "list-of-processors",
          label: "List of  processors",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-phone-codes",
          label: "List of phone codes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-list-by-type",
          label: "Get list by type",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-details-of-selected-processor",
          label: "Get details of selected processor",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-field-mapping-list-for-selected-processor",
          label: "Get field mapping list for selected processor",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "check-users-cluster",
          label: "Check users cluster",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "add-update-processor",
          label: "Add update processor",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-all-code-mapping-list",
          label: "Get all code mapping list",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-data-seers-transaction-code-and-description-of-that-code",
          label: "Get dataSeers transaction code and description of that code",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-code-publish-restore-history",
          label: "Get code publish/restore history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-all-codes",
          label: "Add all codes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-transaction-code",
          label: "Update transaction code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "publish-codes",
          label: "Publish codes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-transaction-code-from-the-list",
          label: "Delete transaction code from the list",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-transaction-details",
          label: "Update transaction details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-download-sample-file-for-code",
          label: "To download sample file for code",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-all-codes",
          label: "Add all codes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-download-code-file-for-all-codes",
          label: "To download code file for all codes.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-get-processor-mapping-publish-history-response",
          label: "To get processor mapping publish history response",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-download-publish-history-response",
          label: "To download publish history response",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "update-the-field-mapping",
          label: "Update the field mapping",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-download-the-sample-file",
          label: "To download the sample file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "delete-field-mapping",
          label: "Delete field mapping",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-field-mapping-for-selected-processor",
          label: "Get field mapping for selected processor",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-get-version-details",
          label: "To get version details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-mask-the-data",
          label: "To mask the data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-processor-filter-list",
          label: "Get processor filter list.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-changed-records",
          label: "Get changed records",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-processor-result",
          label: "Get processor result",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-matrix-data",
          label: "Get matrix data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lock-the-matrix",
          label: "Lock the matrix",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "unlock-the-matrix",
          label: "Unlock the matrix",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "save-matrix-data",
          label: "Save matrix data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-the-program-matrix-data",
          label: "Update the program matrix data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-the-program",
          label: "Delete the program",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "publish-matrix-data",
          label: "Publish matrix data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "program-matrix-publish-restore-history",
          label: "Program matrix publish/restore history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "calculate-the-risk-score-for-all-programs",
          label: "Calculate the risk score for all programs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-matrix-data-by-id",
          label: "Get matrix data by id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-get-publish-history-response",
          label: "To get publish history response",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-download-program-matrix-data",
          label: "To download program matrix data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-unlock-the-records",
          label: "To unlock the records",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-download-publish-history-response",
          label: "To download publish history response",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-start-and-stop-monitoring",
          label: "To start and stop monitoring",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-ach-configuration-list-with-account-prefixes-and-file-name",
          label: "Get ACH configuration list with account prefixes and file name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-program-list-according-to-type-ach-and-bai-2-configuration",
          label: "Get program list according to type(ACH and BAI2 Configuration)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-ach-configuration-details-for-given-id",
          label: "Get ACH configuration details for given id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "save-ach-configuration",
          label: "Save ACH configuration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-ach-configuration",
          label: "Update ACH configuration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-ach-configuration",
          label: "Delete ACH configuration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-bai-2-configuration-list",
          label: "Get BAI2 Configuration list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "save-bai-2-configuration",
          label: "Save BAI2  configuration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-bai-2-configuration",
          label: "Update BAI2 configuration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-bai-2-configuration",
          label: "Delete BAI2 configuration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-get-bai-2-configuration-details",
          label: "To get bai2 configuration details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-of-merchants-added-to-the-platform",
          label: "List of merchants added to the platform",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-merchant-category-codes",
          label: "List of merchant category codes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-a-merchant",
          label: "Add a merchant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-merchant-details-for-mentioned-id",
          label: "Get merchant details for mentioned id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "update-a-merchant",
          label: "Update a merchant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-a-merchant",
          label: "Delete a merchant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-get-details-of-respective-destination",
          label: "To get details of respective destination",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-add-location-for-merchant",
          label: "To add location for merchant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-update-merchant-location",
          label: "To update merchant location",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-update-merchant-location",
          label: "To update merchant location",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-all-ds-transaction-codes",
          label: "Get all ds transaction codes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-ds-transaction-code",
          label: "Add ds transaction code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-ds-transaction-code-details-for-mentioned-id",
          label: "Get ds transaction code details for mentioned id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "update-ds-transaction-code",
          label: "Update ds transaction code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-ds-transaction-code",
          label: "Delete ds transaction code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "publish-ds-codes",
          label: "Publish ds codes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-code-publish-restore-history",
          label: "Get code publish/restore history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-unmap-ds-pos-code",
          label: "To unmap ds POS code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-unmap-ds-transaction-code",
          label: "To unmap ds transaction code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-unmap-ds-authorization-code",
          label: "To unmap ds authorization code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-unmap-ds-network-code",
          label: "To unmap ds network code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-get-publish-history-response",
          label: "To get publish history response",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-download-publish-history-response",
          label: "To download publish history response",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-all-ds-authorization-codes",
          label: "Get all ds authorization codes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-ds-authorization-code",
          label: "Add ds authorization code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-ds-authorization-code",
          label: "Update ds authorization code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-ds-authorization-code-details-for-mentioned-id",
          label: "Get ds authorization code details for mentioned id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "delete-ds-authorization-code",
          label: "Delete ds authorization code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-all-ds-status-codes",
          label: "Get all ds status codes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-ds-status-code-details-for-mentioned-id",
          label: "Get ds status code details for mentioned id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-ds-status-code",
          label: "Add ds status code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-ds-status-code",
          label: "Update ds status code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-ds-status-code",
          label: "Delete ds status code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-all-pos-entry-codes",
          label: "Get all pos entry codes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-ds-pos-entry-code",
          label: "Add ds pos entry code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-ds-pos-entry-code",
          label: "Update ds pos entry Code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-ds-pos-entry-code-details-for-mentioned-id",
          label: "Get ds pos entry Code details for mentioned id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "delete-pos-entry-code",
          label: "Delete pos entry code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-all-ds-network-codes",
          label: "Get all ds network codes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-ds-network-code",
          label: "Add ds network code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-ds-network-code",
          label: "Update ds network code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-ds-network-code-details-for-mentioned-id",
          label: "Get ds network code details for mentioned id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "delete-ds-netrwork-code",
          label: "Delete ds netrwork code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-all-ds-account-type-codes",
          label: "Get all ds account type codes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-ds-account-type-code",
          label: "Add ds account type code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-ds-account-type-code",
          label: "Update ds account type code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-ds-account-type-code-details-for-mentioned-id",
          label: "Get ds account type code details for mentioned id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "delete-ds-account-type-code",
          label: "Delete ds account type code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-all-ds-card-type-codes",
          label: "Get all ds card type codes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-ds-card-type-code",
          label: "Add ds card type code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-ds-card-type-code",
          label: "Update ds card type code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-ds-card-type-code-details-for-mentioned-id",
          label: "Get ds card type code details for mentioned id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "delete-ds-card-type-code",
          label: "Delete ds card type Code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lists-the-quarterly-hidta-hifca-data",
          label: "Lists the quarterly HIDTA/HIFCA data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-hidta-hifca-data-for-mentioned-id",
          label: "Get HIDTA/HIFCA data for mentioned id",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "upload-hidta-hifca-file",
          label: "Upload HIDTA/HIFCA file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-released-by-the-treasury-department",
          label: "List released by the treasury Department",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "details-of-company",
          label: "Details of company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "details-of-compliance-ofac",
          label: "Details of compliance-ofac",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-specific-people-or-groups",
          label: "List of specific people or groups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-download-ofac-data",
          label: "To download OFAC data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-download-cia-world-leaders-data",
          label: "To download cia-world-leaders data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-download-politician-data",
          label: "To download politician data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-download-eu-m-ps-data",
          label: "To download EU MPs data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "details-of-legal-entity",
          label: "Details of legal entity",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "details-of-sanction",
          label: "Details of sanction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-specific-people-or-groups",
          label: "List of specific people or groups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "details-of-legal-entity",
          label: "Details of legal entity",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "details-of-passport",
          label: "Details of passport",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-most-of-the-national-level-cabinet-members-in-world-governments",
          label: "List of most of the national-level cabinet members in world governments",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "details-of-person",
          label: "Details of person",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-of-specific-people-or-groups",
          label: "List of specific people or groups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "details-of-membership",
          label: "Details of membership",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "details-of-organization",
          label: "Details of organization",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "details-of-person",
          label: "Details of person",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-specific-people-or-groups",
          label: "List of specific people or groups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "details-of-membership",
          label: "Details of membership",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "details-of-organization",
          label: "Details of organization",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "details-of-person",
          label: "Details of person",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-account-data",
          label: "Get account data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-permitted-processor-program-group",
          label: "Get permitted processor program group",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-programs",
          label: "Get programs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-an-account",
          label: "Add an account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-an-account",
          label: "Update an account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-account-watchlist-details-by-id",
          label: "Get account watchlist details by id",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-an-account",
          label: "Delete an account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "upload-the-data",
          label: "Upload the data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "publish-the-current-version-of-account-watchlist-to-the-cluster",
          label: "Publish the current version of account watchlist to the cluster",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lock-an-account-watchlist",
          label: "Lock an account watchlist",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "restore-published-version",
          label: "Restore published version",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "unlock-all-items",
          label: "Unlock all items",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-accountholder-data",
          label: "Get accountholder data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-an-accountholder",
          label: "Add an accountholder",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-an-account",
          label: "Update an account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-an-accountholder",
          label: "Delete an accountholder",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-an-accountholder-by-id",
          label: "Get an accountholder by id",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "upload-the-data",
          label: "Upload the data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "publish-the-current-version-of-accountholder-watchlist-to-the-cluster",
          label: "Publish the current version of accountholder watchlist to the cluster",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lock-an-accountholder-watchlist",
          label: "Lock an accountholder watchlist",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "restore-published-version",
          label: "Restore published version",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "unlock-all-items",
          label: "Unlock all items",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-unlock-accountholder-watchlist",
          label: "To unlock accountholder watchlist",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-download-the-accountholder-data",
          label: "To download the accountholder data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-unlock-account-watchlist",
          label: "To unlock account watchlist",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-download-the-account-data",
          label: "To download the account data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-unlock-account-watchlist",
          label: "To unlock account watchlist",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-download-the-merchant-data",
          label: "To download the merchant data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-list-of-merchants",
          label: "Get list of merchants",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-a-merchant-to-merchant-watchlist",
          label: "Add a Merchant to Merchant Watchlist",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-a-merchant",
          label: "Update a merchant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-a-merchant",
          label: "Delete a merchant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "upload-the-data",
          label: "Upload the data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "publish-the-current-version-of-merchant-watchlist-to-the-cluster",
          label: "Publish the current version of merchant watchlist to the cluster",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "restore-published-version",
          label: "Restore published version",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-merchant-details-by-id",
          label: "Get merchant details by id",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lock-a-merchant-watchlist",
          label: "Lock a merchant watchlist",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "unlock-all-items",
          label: "Unlock all items",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-list-of-reason-codes",
          label: "Get list of reason codes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "save-a-reason-code",
          label: "Save a reason code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-reason-code-by-id",
          label: "Get reason code by id",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-a-reason-code-status",
          label: "Update a reason code status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-a-reason-code-fraud-status",
          label: "Update a reason code fraud status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-a-reason-code",
          label: "Update a reason code",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Reports",
      link: {
        type: "doc",
        id: "reports",
      },
      items: [
        {
          type: "doc",
          id: "lists-every-report-available-through-data-seers",
          label: "Lists every report available through DataSeers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-list-of-report-modules",
          label: "Get list of report modules",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-report-details-by-id",
          label: "Get report details by id",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-report-layout-details",
          label: "Get report layout details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lock-a-report",
          label: "Lock a report",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "unlock-a-report",
          label: "Unlock a report",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "add-a-report",
          label: "Add a report",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-a-report",
          label: "Update a report",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "publish-the-current-version-of-report-config-to-the-cluster",
          label: "publish the current version of report config to the cluster",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "restore-the-published-version-of-report-config-to-seerportal",
          label: "Restore the published version of report config to seerportal",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "calculate-the-alert-efficiency",
          label: "Calculate the alert efficiency",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-change-the-report-status",
          label: "To change the report status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-unlock-the-record",
          label: "To unlock the record",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-download-report-config-data",
          label: "To download report config data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-update-report-group-for-user",
          label: "To update report group for user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-download-the-report-containing-less-than-100-records",
          label: "To download the report containing less than 100 records",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-view-the-report",
          label: "To view the report",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-get-ach-file-data",
          label: "To get ach file data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-edit-the-record-in-a-report",
          label: "To edit the record in a report",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-all-reports-available-in-dataseers",
          label: "List of all reports available in dataseers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-all-seer-run-reports-and-their-results",
          label: "List of all Seer-run reports and their results",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "run-a-report",
          label: "Run a report",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-previously-completed-bulk-extracts",
          label: "List of previously completed bulk extracts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-bulk-extracts-sample-files",
          label: "List of bulk extracts sample files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "re-run-bulk-extracts",
          label: "Re-run bulk extracts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "create-adhoc-report",
          label: "Create adhoc report",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "upload-the-file-to-create-adhoc-report",
          label: "Upload the file to create adhoc report",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-bulk-extract",
          label: "Delete bulk extract",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-get-work-unit-status",
          label: "To get work-unit status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-files",
          label: "List of files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-processors",
          label: "List of processors",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-latest-processed-files",
          label: "Get latest processed files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-files-per-processor",
          label: "Get files per processor",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-one-day-files",
          label: "Get one day files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-seven-day-files",
          label: "Get seven day files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-thirty-days-files",
          label: "Get thirty days files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-most-recent-files",
          label: "Get most recent files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-get-list-of-files",
          label: "To get list of files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-get-details-of-file",
          label: "To get details of file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-get-record-type",
          label: "To get record type",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-get-file-records",
          label: "To get file records",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-of-messages-that-are-being-sent-to-data-seers-in-real-time",
          label: "List of messages that are being sent to DataSeers in real time",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-processors",
          label: "List of processors",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "IdentitySeer",
      link: {
        type: "doc",
        id: "identity-seer",
      },
      items: [
        {
          type: "doc",
          id: "get-identityseer-data",
          label: "Get identityseer data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-list-of-flow-config",
          label: "Get list of flow config",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-idv-products",
          label: "Get idv products",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-a-flow-config",
          label: "Add a flow config",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-list-of-scorecard",
          label: "Get list of scorecard",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-user-based-programs",
          label: "Get user based programs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-default-risk-indicators",
          label: "Get default risk indicators",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-score-card-details",
          label: "Get score card details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-a-score-card",
          label: "Add a score card",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "update-a-score-card",
          label: "Update a score card",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-score-card-history",
          label: "Get score card history",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-a-queue-of-previously-requested-kyc-checks",
          label: "Get a queue of previously requested KYC checks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "add-a-kyc-entry",
          label: "Add a KYC entry",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-product-based-flows",
          label: "Get product based flows",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "upload-a-kyc-file",
          label: "Upload a KYC file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-details-for-mentioned-id",
          label: "Get details for mentioned id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-kyc-bulk-details",
          label: "Get kyc bulk details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "download-bulk-upload-result-file",
          label: "Download bulk upload result file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-a-queue-of-previously-requested-kyc-checks",
          label: "Get a queue of previously requested KYC checks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-details-for-mentioned-id",
          label: "Get details for mentioned id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-list-of-idi-countrylist",
          label: "Get list of idi countrylist",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-a-kyc-entry",
          label: "Add a KYC entry",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-a-queue-of-previously-requested-kyb-checks",
          label: "Get a queue of previously requested KYB checks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-details-for-mentioned-id",
          label: "Get details for mentioned id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-a-kyb-entry",
          label: "Add a KYB entry",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "upload-a-kyb-file",
          label: "Upload a KYB file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-a-queue-of-previously-requested-kyb-checks",
          label: "Get a queue of previously requested KYB checks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-a-kyb-entry-outside-of-the-u-s",
          label: "Add a KYB entry outside of the U.S",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-a-api-remaining-count",
          label: "Get a api remaining count",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-search-the-data-in-idbi",
          label: "To search the data in IDBI",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-add-extra-api-count-in-idbi",
          label: "To add extra api count in IDBI",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-download-the-file",
          label: "To download the file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-get-conversation-details",
          label: "To get conversation details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-a-kyc-entry",
          label: "Add a KYC entry",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-a-officer-list-for-selected-company",
          label: "Get a officer list for selected company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-a-officer-data-for-selected-company",
          label: "Get a officer data for selected company",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-details-of-selected-company",
          label: "Get details of selected company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-a-queue-of-previously-requested-kyc-checks",
          label: "Get a queue of previously requested KYC checks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-details-for-mentioned-id",
          label: "Get details for mentioned id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-a-kyc-entry",
          label: "Add a KYC entry",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-a-queue-of-previously-requested-kyc-checks",
          label: "Get a queue of previously requested KYC checks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-details-for-mentioned-id",
          label: "Get details for mentioned id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-a-kyc-entry",
          label: "Add a KYC entry",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "upload-a-kyc-file",
          label: "Upload a KYC file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-a-list-of-client",
          label: "Get a list of client",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "add-a-client-information-including-phone-number",
          label: "Add a client information including phone number",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-details-for-mentioned-id",
          label: "Get details for mentioned id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-a-list-of-client",
          label: "Get a list of client",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "add-a-company-information",
          label: "Add a company information",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-details-for-mentioned-id",
          label: "Get details for mentioned id",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-a-queue-of-previously-requested-kyc-checks",
          label: "Get a queue of previously requested KYC checks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "add-a-kyc-entry",
          label: "Add a KYC entry",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-details-for-mentioned-id",
          label: "Get details for mentioned id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-a-queue-of-previously-requested-kyc-checks",
          label: "Get a queue of previously requested KYC checks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-details-for-mentioned-id",
          label: "Get details for mentioned id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-a-kyc-entry",
          label: "Add a KYC entry",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "verify-a-kyc-entry",
          label: "Verify a KYC entry",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-a-queue-of-previously-requested-kyc-checks",
          label: "Get a queue of previously requested KYC checks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-details-for-mentioned-id",
          label: "Get details for mentioned id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-a-kyc-entry",
          label: "Add a KYC entry",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-add-kyc-details",
          label: "To add KYC details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-of-assigned-users",
          label: "List of assigned users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-of-unrestricted-flows",
          label: "List of unrestricted flows",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-details-of-webhook-event",
          label: "Get details of webhook event",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "add-a-history",
          label: "Add a history",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-get-compliance-files",
          label: "To get compliance files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reflect-a-queue-of-previously-requested-kyc-kyb-checks",
          label: "Reflect a queue of previously requested KYC/KYB checks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "save-business-information",
          label: "Save business information",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-details-about-mentioned-id",
          label: "Get details about mentioned id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-details-of-flow-history",
          label: "Get details of flow history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "save-customer-information",
          label: "Save customer information",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-details-about-mentioned-id",
          label: "Get details about mentioned id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-list-for-dropdowns",
          label: "Get list for dropdowns",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "ReconSeer",
      link: {
        type: "doc",
        id: "recon-seer",
      },
      items: [
        {
          type: "doc",
          id: "shows-a-simple-daily-ledger-of-credit-and-debits-that-are-happening-within-the-platform",
          label: "Shows a simple daily ledger of credit and debits that are happening within the platform",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-list-of-alerts",
          label: "Get list of alerts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-user-processor-program-list",
          label: "Get user processor program list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-list-of-cases-alert-users",
          label: "Get list of cases alert users",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "add-a-alert",
          label: "Add a alert",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-alert-details-for-selected-id",
          label: "Get alert details for selected id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lock-selected-alert",
          label: "Lock selected alert",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "update-an-alert",
          label: "Update an alert",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "assign-multiple-alerts",
          label: "Assign multiple alerts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "unlock-selected-alert",
          label: "Unlock selected alert",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "displays-the-statistics-on-the-how-long-alerts-have-been-in-unassigned-open-or-in-progress-status-also-visualizes-alerts-open-by-day-and-alerts-worked-by-day",
          label: "Displays the statistics on the how long alerts have been in unassigned, open, or in progress status, also visualizes alerts open by day and alerts worked by day",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "enhance-person",
          label: "Enhance person",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-roll-forward-latest-report",
          label: "Get roll forward latest report",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-data",
          label: "Get data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-data-about-roll-forward-network-settlement",
          label: "Get data about roll forward network settlement",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "roll-forward-search",
          label: "Roll forward search",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-transaction-matching-list",
          label: "Get transaction matching list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-transaction-matching-data",
          label: "Get transaction matching data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-match-the-transaction-data",
          label: "To match the transaction data",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "ComplianSeer",
      link: {
        type: "doc",
        id: "complian-seer",
      },
      items: [
        {
          type: "doc",
          id: "to-upload-the-file-in-alerts",
          label: "To upload the file in alerts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-download-the-alert",
          label: "To download the alert",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-download-uploaded-file-in-alert",
          label: "To download uploaded file in alert",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-update-alert-report-details",
          label: "To update alert report details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-alert-account-list",
          label: "Get alert account list",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-download-report-details",
          label: "To download report details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-download-alert-data",
          label: "To download alert data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-get-list-of-alerts-by-metrics",
          label: "To get list of alerts by metrics",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-reopen-the-alert",
          label: "To reopen the alert",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-case-alert-details-by-id",
          label: "Get case alert details by id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-case-history-details-by-id",
          label: "Get case history details by id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-get-escalated-user-list",
          label: "To get escalated user list",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-download-the-uploaded-file",
          label: "To download the uploaded file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-revert-the-alert",
          label: "To revert the alert",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-complianseer-count-data",
          label: "Get complianseer count data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-list-of-reports",
          label: "Get list of reports",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-list-of-cases",
          label: "Get list of cases",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-list-of-sar-details",
          label: "Get list of sar details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-list-of-escalated-users",
          label: "Get list of escalated users",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "create-a-case-from-alert",
          label: "Create a case from alert",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-active-case-list",
          label: "Get active case list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-alert-triggered-chart-data",
          label: "Get alert triggered chart data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "create-a-new-case",
          label: "Create a new case",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-case-details-by-id",
          label: "Get case details by Id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lock-the-mentioned-case",
          label: "Lock the mentioned case",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "assign-a-case",
          label: "Assign a case",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "unlocked-all-cases",
          label: "Unlocked all cases",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-details-for-sar-ctr",
          label: "Add details for SAR/CTR",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-client-by-id",
          label: "Get client by id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lock-a-mentioned-sar-id",
          label: "Lock a mentioned sar id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "sar-change-history",
          label: "SAR change history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "sar-timeline",
          label: "SAR timeline",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-sar-data",
          label: "Get sar data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "update-sar-details",
          label: "Update sar details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "u-pdate-sar-status",
          label: "UPdate sar status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "unlock-the-sar",
          label: "Unlock the sar",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-modify-the-sar",
          label: "To modify the sar",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-update-assignee",
          label: "To update assignee",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-get-details",
          label: "To get details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-sample-file",
          label: "Get sample file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-download-dispute-details",
          label: "To download dispute details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-download-reg-e-monitoring-data",
          label: "To download Reg-E monitoring data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-upload-the-document",
          label: "To upload the document",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-download-the-uploaded-document",
          label: "To download the uploaded document",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-download-the-uploaded-document",
          label: "To download the uploaded document",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "to-download-disputes",
          label: "To download disputes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-disputes-list",
          label: "Get disputes list",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "insert-disputes",
          label: "Insert disputes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "insert-dispute-details",
          label: "Insert dispute Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-dispute-details-for-mentioned-uuid",
          label: "Get dispute details for mentioned uuid",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-dispute-steps",
          label: "Get dispute steps",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "FraudSeer",
      link: {
        type: "doc",
        id: "fraud-seer",
      },
      items: [
        {
          type: "doc",
          id: "get-fraudseer-count-data",
          label: "Get fraudseer count data",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "StrataSeer",
      link: {
        type: "doc",
        id: "strata-seer",
      },
      items: [
        {
          type: "doc",
          id: "get-transaction-layout-data",
          label: "Get transaction layout data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-mastet-data",
          label: "Get mastet data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "to-get-alert-list",
          label: "To get alert list",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-transaction-data",
          label: "Get transaction data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-transaction-kyc-tree-data",
          label: "Get transaction kyc tree data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-flow-step-status",
          label: "Get flow step status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-transaction-related-data",
          label: "Get transaction related data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-transaction-alert-cases-data",
          label: "Get transaction alert cases data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-master-address-data",
          label: "Get master address data",
          className: "api-method get",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
